### ISSUE TITLE
Where to copy the model?

### ISSUE THREAD

**Issue by Tobe2d** [if-ai/ComfyUI-IF_AI_tools#1]
I downloaded Hermes-2-Pro-Mistral-7B.Q3_K_L but it is not clear where to copy this filse so it will be detected in IF Prompt to Prompt💬 node.

Could you help on this?

**Comment by if-ai** [comment]
like in the video here https://youtu.be/QAnapTWnawU?si=CeTrt9GSdcwIUtQl&t=454
1)_. install ollama 

2)_. Go into your terminal and type: ollama run adrienbrault/nous-hermes2pro:Q5_K_S

That will install the model and then you can ask any question to it.

3)_. Go to your ComfyUI custom_nodes folder type CMD in the address bar it will open command prompt terminal.

Type: git clone https://github.com/if-ai/ComfyUI-IF_AI_tools.git

That will install the custom node.

Now you can start ComfyUI and load the custom workflow that is on the workflows folder inside the custom_nodes\ComfyUI-IF_AI_tools\workflows folder you can run the queue to generate an image

**Comment by Tobe2d** [comment]
Thanks for the reply, now it works!

**Comment by if-ai** [comment]
Thanks
