### ISSUE TITLE
how to use Proteus-RunDiffusion  model in ollama?

### ISSUE THREAD

**Issue by czcz1024** [if-ai/ComfyUI-IF_AI_tools#10]
you recommand this model,but it's a huggingface link
how could i use it in ollama?

**Comment by if-ai** [comment]
The hugging face links are for stable diffusion models the link on the readme is the same model but has been update so it is better get the one from the readme get the withoutclip and use bail blessed vae or the bae VAE that is inside the models the fixed sdxl VAE by mybiolin should work too
