### ISSUE TITLE
Nodes failing to load ...

### ISSUE THREAD

**Issue by Torcelllo** [if-ai/ComfyUI-IF_AI_tools#106]
Log 
[IF_AI_Tools_comfyui.log](https://github.com/user-attachments/files/16836924/IF_AI_Tools_comfyui.log)

![IF_AI_Tools](https://github.com/user-attachments/assets/666eab41-01b6-4742-983c-d8e18961ef77)

**Comment by Torcelllo** [comment]
Manual d/load via Manager fails

[Log2comfyui.log](https://github.com/user-attachments/files/16836982/Log2comfyui.log)

**Comment by Torcelllo** [comment]
I have set my ComfyUI Manager security level to "weak"

**Comment by dzy1128** [comment]
The same question.Did you solve it?

**Comment by Torcelllo** [comment]
Not yet ...

**Comment by if-ai** [comment]
did you follow step 3 Move the IF_AI folder from the ComfyUI-IF_AI_tools to inside the root input ComfyUI/input/IF_AI ?

**Comment by Torcelllo** [comment]
Works! Hurray!  Thank you!  :)
