### ISSUE TITLE
Different LLM Server

### ISSUE THREAD

**Issue by Paritybit01** [if-ai/ComfyUI-IF_AI_tools#11]
What if i wanted to use LM Studio? Which file would i have to add the configuration to? Also thanks for this. Great work.

**Comment by if-ai** [comment]
Hi, I am working on a current update and the next update after that one I will add LM studio and open router

**Comment by Paritybit01** [comment]
Actually bro, it pretty much works using Ollama name and the port num for LM Studio. Go figure. But yeah, sounds good and thanks for the quick reply.

**Comment by Paritybit01** [comment]
welp, fer some reason it just shit the tub...was working. Time to dive in and play with some nodes hehe.

**Comment by if-ai** [comment]
oh great thanks for letting me know. they must be using the same OPENAI API standard, then I will close this issue thanks
