### ISSUE TITLE
Prompt | Image to Prompt is not working

### ISSUE THREAD

**Issue by jakechai** [if-ai/ComfyUI-IF_AI_tools#119]
After the recent update, I found that the repo name has been changed from `ComfyUI-IF_AI_tools` to `ComfyUI_IF_AI_tools`. ComfyUI Manager is still using the old name, which breaks everything.

I manually cloned the latest repo and found that the Prompt to Prompt | Image to Prompt is not working, as is the Chat Prompt Node error.
Is this related to the name change?
![ollama not working](https://github.com/user-attachments/assets/4f70f686-d7ed-4f7e-8bf1-77459b1a621a)

**Comment by if-ai** [comment]
Sorry, I am refactoring the node today, I will completly replace it with a new node just for SD that will do the same fuctions and some more but with the same amount of parameters, It will keep the same name to not break workflows but it might be slightly bigger or smaller in size.

**Comment by kendy2013** [comment]
更新了之后，很多节点没法用，与上面楼主报同样的错误，什么时候能够修复？而且gitclone的文件少了很多

**Comment by jakechai** [comment]
It works now.
