### ISSUE TITLE
Image to Prompt Issue with OpenAI and Claude models

### ISSUE THREAD

**Issue by cywale** [if-ai/ComfyUI-IF_AI_tools#12]
Hi, 

I'm trying to use the IF_ImageToPrompt node to analyze images, and both openai gp4 vision and claude3 options are not generating any prompts.

I have exported the api keys properly and the IF_PromptToPrompt is working fine, so the api key is good. 

I've also tested with the comfyui_llmvision module, and claude3 and gpt4vision are working with that also.

The IF_ImageToPrompt note just displays the characters: 'E', 'x', and 'c' on the Question, Response and Negative outputs respectively. Here's a screenshot of the output:

![Screen Shot 2024-04-13 at 18 59 58](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/106493194/4a381d56-6932-4d22-847c-a86c51d7c5ba)

I get the error `Exception occurred: 'IFImagePrompt' object has no attribute 'openai_api_key'` on the backend

![Screen Shot 2024-04-13 at 18 53 03](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/106493194/4463702c-cbf7-42ba-b98a-093018da155b)

please assist.

**Comment by if-ai** [comment]
Oh sorry I updated the node now, I did fix this last time and somehow did not update the correct file, should be working now please update and recreate the node if necessary
