### ISSUE TITLE
image to prompt not working (prompt saying the image is not visible)

### ISSUE THREAD

**Issue by andrew-b-park** [if-ai/ComfyUI-IF_AI_tools#13]
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/98562901/eb37b76e-d77c-4952-8cc3-3bcb1c3362b1)
hello, when using the if image to prompt node, i dont think the result is matching the image. Using mistral model.

Is there anything i set up wrong?

**Comment by andrew-b-park** [comment]
bakllava works, not for the rest of the models.

**Comment by if-ai** [comment]
Hi, The image prompt only works when choosing a multimodal models like the
Llava and baklava or gpt4 vision and Opus Sonnet and Haiku via API. Normal
text models will reply but won't be able to actually understand the image
