### ISSUE TITLE
ComfyUI-IF_AI_tools Nodes Fail to Load

### ISSUE THREAD

**Issue by Kad001** [if-ai/ComfyUI-IF_AI_tools#14]
Updated Comfyui and since then the ComfyUI-IF_AI_tools Nodes Fail to Load.
Have tried reinstalling, uninstalling etc no success.
It was working well till i run the update.

ComfyUI-IF_AI_tools: last update: 2024-04-13

ERROR Message:

## ComfyUI-Manager: EXECUTE => ['/home/kad/comfy/comfy_env/bin/python3', '-m', 'pip', 'install', 'dlib']
 Collecting dlib
   Using cached dlib-19.24.4.tar.gz (3.3 MB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'done'
   Preparing metadata (pyproject.toml): started
   Preparing metadata (pyproject.toml): finished with status 'done'
 Building wheels for collected packages: dlib
   Building wheel for dlib (pyproject.toml): started
   Building wheel for dlib (pyproject.toml): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   × Building wheel for dlib (pyproject.toml) did not run successfully.
[!]   │ exit code: 1
[!]   ╰─> [10 lines of output]
[!]       running bdist_wheel
[!]       running build
[!]       running build_ext
[!]       Traceback (most recent call last):
[!]         File "/home/kad/comfy/comfy_env/bin/cmake", line 5, in <module>
[!]           from cmake import cmake
[!]       ModuleNotFoundError: No module named 'cmake'
[!]
[!]       ERROR: CMake must be installed to build dlib
[!]
[!]       [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!]   ERROR: Failed building wheel for dlib
[!] Failed to build dlib
 ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects
install script failed: https://github.com/if-ai/ComfyUI-IF_AI_tools

.
.
.
.
.

[!] ERROR: Invalid requirement: '#sudo apt-get install libsox-fmt-all'
install script failed: https://github.com/if-ai/ComfyUI-IF_AI_tools

**Comment by akshay-sdixit** [comment]
One workaround is to go to the previous commit in Git, download the ZIP file of that version, and paste it into the custom node. This worked for me.

**Comment by if-ai** [comment]
Hi thank you, seems like intalling dlib is tricky sometimes
activate your comfy environment
if `pip install dlib --verbose` does not work
run `sudo apt-get install cmake` try again if it still doesn't work 
go to 
https://github.com/davisking/dlib clone the repo to any location
`git clone https://github.com/davisking/dlib.git`
got to the root of the repo and run `python setup.py install` all while your comfy env is active 

I deleted that stupid line '#sudo apt-get install libsox-fmt-all' sorry

**Comment by Kad001** [comment]
Thanks for the response.
Pip install dlib threw this error:
Building wheels for collected packages: dlib
Running command Building wheel for dlib (pyproject.toml)
running bdist_wheel
running build
running build_ext
Traceback (most recent call last):
File "/home/kad/comfy/comfy_env/bin/cmake", line 5, in <module>
from cmake import cmake
ModuleNotFoundError: No module named 'cmake'

ERROR: CMake must be installed to build dlib

error: subprocess-exited-with-error

× Building wheel for dlib (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
full command: /home/kad/comfy/comfy_env/bin/python3 /home/kad/comfy/comfy_env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpfho_d4_k
cwd: /tmp/pip-install-db65jyax/dlib_5330716999694f5cba726118ad9554c0
Building wheel for dlib (pyproject.toml) ... error
ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects(comfy_env) ***@***.***:~/ComfyUI/dlib$

Installing Cmake:
(comfy_env) ***@***.***:~/ComfyUI/dlib$ sudo apt-get install cmake
[sudo] password for kad:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

After cloning the dlib repo:
(comfy_env) ***@***.***:~/ComfyUI/dlib$ python setup.py
/home/kad/ComfyUI/dlib/setup.py:35: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
from distutils import log
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: no commands supplied

So still not working

Thanks
