### ISSUE TITLE
Ollama keep_alive:

### ISSUE THREAD

**Issue by ekondev** [if-ai/ComfyUI-IF_AI_tools#17]
By default ollama keeps the last loaded model in the vram for 5 min. Could you please add a keep_alive: 0 to flush it right after the generation and free up the vram for comfy? I've tried to add it manually but it only works on image to prompt node, prompt to prompt fails for some reason. [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately)

**Comment by if-ai** [comment]
Right, good idea I will add it later thanks for the suggestion

**Comment by if-ai** [comment]
> By default ollama keeps the last loaded model in the vram for 5 min. Could you please add a keep_alive: 0 to flush it right after the generation and free up the vram for comfy? I've tried to add it manually but it only works on image to prompt node, prompt to prompt fails for some reason. [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately)

I added the feature now you can select to keep them on memory or by default the immediately unload after generation
