### ISSUE TITLE
Can't find the directory?

### ISSUE THREAD

**Issue by alex13by** [if-ai/ComfyUI-IF_AI_tools#18]
D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-IF_AI_tools\dreamtalk\configs\default.py
If in such a location, the plugin will not run and cannot find the directory, but I want to use my own directory name

The location causing the error:

def find_comfy_dir(current_path):
    """ Recursively search for a directory named 'ComfyUI' starting from the current path. """
    if os.path.basename(current_path) == 'ComfyUI':
        return current_path
    else:
        parent_path = os.path.dirname(current_path)
        if parent_path == current_path:  # if reached the root of the directory tree
            raise Exception("ComfyUI directory not found")
        return find_comfy_dir(parent_path)

**Comment by if-ai** [comment]
Does it work now? there is been an update and it should be working now
