### ISSUE TITLE
The purple area is dimmed. 

### ISSUE THREAD

**Issue by nothingness6** [if-ai/ComfyUI-IF_AI_tools#2]
![If_Ai](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/105210258/909f0b75-fd4d-4fb1-8944-d421c9ccadb0)
As you can see in the screenshot above, the purple area seems dimmed, so it's hard to read the text. 
How do I change it?

**Comment by if-ai** [comment]
Hi, Ctrl +B bypass the nodes but at the moment the last update of ollama has a bug with Llava visual models they will fix it soon. If you want to use this feature you are going to need version 0.1.25 of ollama and if you are on Windows you need to use a firewall rule so it doesn't auto update. Please wait for the next ollama they told me they are working on fixing it as soon as they can.

**Comment by nothingness6** [comment]
> Hi, Ctrl +B bypass the nodes but at the moment the last update of ollama has a bug with Llava visual models they will fix it soon. If you want to use this feature you are going to need version 0.1.25 of ollama and if you are on Windows you need to use a firewall rule so it doesn't auto update. Please wait for the next ollama they told me they are working on fixing it as soon as they can.

I see. Thx for the answer!
