### ISSUE TITLE
Additional negative prompt not recognize.

### ISSUE THREAD

**Issue by razvanab** [if-ai/ComfyUI-IF_AI_tools#20]
I try to add new negative prompts in the neg_prompts.json file, but the response is always:  Message will appear here.

I added this after:  "None": "None",
"Mine": "text, logo",

**Comment by if-ai** [comment]
Hi, it will appear the next session, next time you start comfy.

**Comment by razvanab** [comment]
Yes, I tried that and it is the same.

**Comment by if-ai** [comment]
dare you sure the file actually save

**Comment by razvanab** [comment]
Yes.
Ok, for some reason today it's working fine, and I have no idea what changed.

**Comment by if-ai** [comment]
thank you for closing the issue, one more thing maybe you know this but when working with json try to save encoding UFT-8 sometimes there are weird characters and it would throw an error . Ty
