### ISSUE TITLE
can i use the old version ? 

### ISSUE THREAD

**Issue by CodeGrafus** [if-ai/ComfyUI-IF_AI_tools#21]
After updating (I use ComfyUI windows portable) I cannot use the new version no matter what I do.  Is it possible to install and use the old version ?

**Comment by if-ai** [comment]
Please Try updating now, I separated all the nodes that were bloating the AI_tools now you can choose to use them as separate custom nodes the links are in the readme for the other repos. Thanks

**Comment by CodeGrafus** [comment]
Thank you for providing a very quick solution. I am grateful..
