### ISSUE TITLE
IF chat prompt does't get the image

### ISSUE THREAD

**Issue by blueraincoatli** [if-ai/ComfyUI-IF_AI_tools#22]
I load a image to IF chat prompt image input, and ask for describing the picture, but the response is not correct,, it seems that the node does't get the image. 
![微信截图_20240424200216](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/142435478/95c26444-78cf-48a2-829c-223f0fa3d71e)

**Comment by if-ai** [comment]
Yes for images you need a multi-modal model LlaMA3 is just for text here is a link for a LLaVa1.6 `ollama run llava:7b-v1.6-mistral-q5_0` you can also see all the available models here on this list the bigger they are the better quality you get but also take more resources like vram etc.. https://ollama.com/library/llava if you click on the latest dropdown you can check them up

**Comment by blueraincoatli** [comment]
It works after I get the llava switch the model in the IF-AI node, thank you very much!

**Comment by if-ai** [comment]
Thank you, I will close the issue then

**Comment by hanL34** [comment]
After running the command "ollama run llava" the model is automatically downloaded to the C drive, do I need to move the model to a certain folder, my node does not recognize the model! thanks
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/127322778/03ac6219-e2c7-49d4-b1fb-8a780c001237)
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/127322778/41e472f3-ae3f-4aad-91d0-693027e69c19)

**Comment by if-ai** [comment]
no if ollama is running it should see the model if you open your terminal and type `ollama list` and llava is listed it should be also in comfy is the same command. so if llama service is running comfy should see it

**Comment by hanL34** [comment]
> no if ollama is running it should see the model if you open your terminal and type `ollama list` and llava is listed it should be also in comfy is the same command. so if llama service is running comfy should see it

thanks,I'm going to reinstall 0.1.25, I had the latest version installed previously

**Comment by if-ai** [comment]
No the very last version works fine I have been using it they fix that issue

**Comment by hanL34** [comment]
> No the very last version works fine I have been using it they fix that issue

Sorry to interrupt again, I reinstalled 0.1.25 and still can't load ollama's model, and the reply given by claude3 doesn't seem to help!
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/127322778/327e2e37-81d6-4f1f-b253-f621a595abd7)
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/127322778/6af48af2-ef42-45c8-8039-529ac6501f88)

**Comment by if-ai** [comment]
if you are in the same computer try writing 127.0.0.1 as base ip instead of localhost could you give it a try please

**Comment by if-ai** [comment]
![explorer_Jn3yHmU92p](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/21185218/0e47e5c3-5af4-45b3-9bb4-c7fafcdd6a31)
in your username in your computer locate that file open it see any message with source=routes to check if that is your base_ip
![notepad_gliJHrD8Gi](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/21185218/31b4ea81-8569-4e02-bb54-0d0be1a51821)

**Comment by Linaghan34** [comment]
> if you are in the same computer try writing 127.0.0.1 as base ip instead of localhost could you give it a try please

这对我有效，太感谢了，这个文件我找到了，和您说的一样
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/127322778/dd164ec5-39e7-486e-842b-68d3ec070042)

**Comment by hanL34** [comment]
> > if you are in the same computer try writing 127.0.0.1 as base ip instead of localhost could you give it a try please
> 
> its worked for me, thanks so much, I found this file and it's exactly what you said
 ![image](https://private-user-images.githubusercontent.com/127322778/326522053-dd164ec5-39e7-486e-842b-68d3ec070042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTEwNjUsIm5iZiI6MTcxNDQxMDc2NSwicGF0aCI6Ii8xMjczMjI3NzgvMzI2NTIyMDUzLWRkMTY0ZWM1LTM5ZTctNDg2ZS04NDJiLTY4ZDNlYzA3MDA0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNzEyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2QxZDJhOTdlYzY4OTczNDM0OGE2NzZkNjhjYTY5ZGU2ZmNkNmE3ZThhZmZjZDVlNGJhZjEzM2YyZTU5NGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0RAXsFdEb6VxHrnq7BHQJ9DasaUsQ9pkIflDFI7vAfI)

**Comment by if-ai** [comment]
nice thanks, glad it works now
