### ISSUE TITLE
Possibility to input a profile description directly in the node.

### ISSUE THREAD

**Issue by alonsojr1980** [if-ai/ComfyUI-IF_AI_tools#24]
First of all, thanks for the amazing node! It would be great if you allowed the user to also input a profile text directly in the node, instead of having to edit the "profiles.json".  Thanks!

**Comment by if-ai** [comment]
Thanks for the suggestion, Yes I plan to add this.

**Comment by PrometheusDante** [comment]
That would be a nice feature indeed. Thank you!

**Comment by if-ai** [comment]
Now you can add the assistant description with the Prime directives input Sorry I took this long
