### ISSUE TITLE
About breaking changes

### ISSUE THREAD

**Issue by alonsojr1980** [if-ai/ComfyUI-IF_AI_tools#25]
Hello! Every commit you make you break working workflows. I use ComfyUI's API a lot and it requires that all REQUIRED fields are sent with the POST json. Please, when you add new fields like "top_p" and "top_k", make them OPTIONAL with the OLLAMA's recommended default value. Thanks!
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/13320570/fc1acc7b-a3af-4a99-bd52-2e19da3d0a8e)

**Comment by if-ai** [comment]
Sorry. I wasn't aware of that I'll be more careful, thank you. Maybe I can drag those as optional. Would that be okay?

**Comment by alonsojr1980** [comment]
Sure! Don't forget to add the default values to those parameters in your "def describe_picture( )". Thank you very much!

**Comment by if-ai** [comment]
Okay I now move most of the parameters to optional and I am passing unto describe. I also unify the nodes into one and this looks to be more solid solution going forward to not break workflows the IFChatPrompt Node now will contain an SD mode.
