### ISSUE TITLE
Custom presets

### ISSUE THREAD

**Issue by razvanab** [if-ai/ComfyUI-IF_AI_tools#26]
I have a small request.
Every time the extension is updated, my custom presets are overwritten. I was wondering if you could somehow make a separate folder for custom presets and the one you add to be the "build-in" ones.
Thank you.

**Comment by if-ai** [comment]
Thanks I will try to add that

**Comment by if-ai** [comment]
In the new latest version I m using a new strategy. I move it to the root of ComfyUI you need to download the folder IF_AI from the repo here and move it inside the input I:\ComfyUI\input\IF_AI that way it will never overwrite again unless you do it on purpose. Hope it helps

**Comment by razvanab** [comment]
Yeah, I like how this works now. Thank you, sir.
