### ISSUE TITLE
Phi-3 models

### ISSUE THREAD

**Issue by ghostrunner-art** [if-ai/ComfyUI-IF_AI_tools#28]
Dear, thank you for your contribution to community open source. 
I wonder if you are interested in training a model for "Phi-3-mini-4k-instruct-q4", which is only a little over 2GB in size. This will save more resources and result in faster response. Very suitable for efficient writing of prompts.
https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf
I am currently using the version of phi3, which has no trained model and the performance is not good.
https://ollama.com/library/phi3
Really looking forward to your new model.

---- The above is from Google Translate, please forgive me if it offends you.

**Comment by razvanab** [comment]
I was thinking the same, but it's better to wait for a dolphin version of Phi-3, which will be more open and uncensored. Until then, I recommend using the dolphin version of Lama 3.

**Comment by if-ai** [comment]
![0necv9BURN](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/21185218/1ae7d366-33bd-4cc9-8c97-0f2cce9c7158)
Made a test version with PHi3 I think I missed a couple of things but it kind of works. I will remake this with an orthogonalized version of this when I get a chance

**Comment by ghostrunner-art** [comment]
Thank you very much for your contribution, and look forward to your PHI3 version model, which has great significance for low configuration computers. We look forward to uploading the PHi3 model to Ollama.@if-ai

**Comment by if-ai** [comment]
> Thank you very much for your contribution, and look forward to your PHI3 version model, which has great significance for low configuration computers. We look forward to uploading the PHi3 model to Ollama.@if-ai
I have the new ollma phi3 dolphin model here https://ollama.com/impactframes/ifai_promptmkr_dolphin_phi3 or you can just run 
`ollama run impactframes/ifai_promptmkr_dolphin_phi3:latest`
