### ISSUE TITLE
Meaning of "profile" and "temperature"

### ISSUE THREAD

**Issue by karl-von-knecht** [if-ai/ComfyUI-IF_AI_tools#29]
Hi IF-AI,
thanks for your nodes, they work great for me.
I am curious what the profile and temperature parameters do, can you please explain? 
Thank you for your kindness!

**Comment by if-ai** [comment]
Hi, Thank you. The profile soon to be named (assistant) is kind of a system prompt or template for the LLM to control it's behaviour.  I am working to improve this node and making it into something that can be an assistant for your workflows in comfy for a wide range of scenarios. Still a long way to go.  But the idea is to steer the model to be more specific to your use case. The profiles are json files so you can create your own assistants. 
The Temperature is a parameter to control how creative and coherent you want your response, if the responses are too wild you can lower this number normally it goes from 0 - 2 a number closer to zero like 0.2  will give a very strict and repetitive output 0.5-0.7 is a good number to get creativity and avoid repetitiveness you can go over one like 1.2 but depends on the models some have different thresholds and can make the response incoherent to your request. This numbers are base on LLama models but even a finetune can skew the numbers so you have to play a little to find the best settings.

**Comment by karl-von-knecht** [comment]
Great explanation, thanks! You might consider adding this information to the Usage instructions where people are more likely to find it than buried here in Issues.

**Comment by if-ai** [comment]
I am preparing some updates and will make a better docs for the nodes soon after the update. Since things are like in a WIP phase atm. Thanks for the suggestion

**Comment by if-ai** [comment]
I added a help Instructions guide Note in the latest workflow
