### ISSUE TITLE
Image Input

### ISSUE THREAD

**Issue by Mossbraker** [if-ai/ComfyUI-IF_AI_tools#3]
Could you possibly have an alt version of the IF Image to Prompt node that has an input for an image or image batch? Currently, if you convert the 'image' widget to an input, it doesn't accept images to the input as it is combo type. 

I tried to do this myself, but always unsuccessfully as I don't know what I'm doing. Initial error was that pic had 4 dimensions, but should be 2/3 dimensional, so I used squeeze to remove what I think was the batch dimension. Tried to manipulate that a few different ways before doing b64encode, but I always got "Failed to fetch response, status code: 400" which also prints the response "Failed to fetch response from Ollama."

An updated node, or a suggestion to help me figure the rest out myself, would be greatly appreciated.

**Comment by if-ai** [comment]
I am working on adding batch images I see if can add alternative inputs too. I will reply with the update here

**Comment by if-ai** [comment]
I added the input image
