### ISSUE TITLE
Load Image Node not working 

### ISSUE THREAD

**Issue by INTstinkt** [if-ai/ComfyUI-IF_AI_tools#30]
When trying to get a Prompt with the load image Node i get random prompts with llama 3 ifai sd prompt mkr. when using IFPromptMKR IMG

**Comment by if-ai** [comment]
Yes llama 3 is not multimodal ifai sd prompt mkr is just for text prompts, I will make it one that is multimodal but for now you can use [llava:7b-v1.6-mistral-q5_K_M](https://ollama.com/library/llava:7b-v1.6-mistral-q5_K_M) or any llava or vision model
