### ISSUE TITLE
oobabooga

### ISSUE THREAD

**Issue by drago87** [if-ai/ComfyUI-IF_AI_tools#31]
Would it be possible to add oobabooga as a backend?

**Comment by if-ai** [comment]
Yes, I will add it too thanks for reminding me

**Comment by if-ai** [comment]
I added ooga booga the name is textgen works fine but I haven't tested it too much so  please let me know 
![thorium_E9ib4kMrNb](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/21185218/3d435b62-02e6-4364-856c-040d92b90599)
![C3gVZNyz8e](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/21185218/41aae2f5-e52e-4a96-a15d-607ce8330434)
please use the SD mode and select the character I am not sure If I am passing system prompt I will check but is working fine with my old llama2 gptq finetune 
![CRovzoLUoW](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/21185218/4b8e9fe2-1099-4f63-b6eb-1212d25db8de)

is only Available on IFChatPromptNode which incorporates the other two nodes functions into one

**Comment by if-ai** [comment]
port is 5000 for ooga
