### ISSUE TITLE
Fixed seeds don't work?

### ISSUE THREAD

**Issue by liulsg** [if-ai/ComfyUI-IF_AI_tools#33]
When the seed is fixed, it can still generate new content, I don't know if I used it wrong or was designed to do so

**Comment by ThomasRoyer24** [comment]
> When the seed is fixed, it can still generate new content, I don't know if I used it wrong or was designed to do so

i've encountered the same problem. In reality, it all depends on the model and assistant you choose. i personally recommend lyricrafter as an assistant and llama3 as a model. In any case, even if the seed changes, your answers will always be very similar, so don't worry.

**Comment by liulsg** [comment]
@ThomasRoyer24 
The main role of this plug-in is prompt words, if you can not fix the seed, then each time you have to call the model to regenerate, prompt words slightly change the content generated will change, but also will take up more memory.

**Comment by if-ai** [comment]
> @ThomasRoyer24 The main role of this plug-in is prompt words, if you can not fix the seed, then each time you have to call the model to regenerate, prompt words slightly change the content generated will change, but also will take up more memory.

Yes I am trying to fix this with some engines might not be possible I am not entirely sure if this might be useful for you, but a workaround to keep the same exact output is to just mute or bypass the node and have the output display text with the previous response  connected to the conditioning. I also think that is better than just using fixed seed for the purpose of repeating the same prompt

**Comment by liulsg** [comment]
@if-ai thanks, jJust mute or bypass nodes Yes, thank you

**Comment by if-ai** [comment]
Thanks I will close the issue now. I added seed to all the engines except Groq and anthropic. But as far as I can tell the seed is not the same like in comfy even if you have same seed the api still send a request even if you get the same response still process so is better to press CTRL+M to mute the node until needed again on the workflow
