### ISSUE TITLE
IMG2 Prompt (Text) not working for me

### ISSUE THREAD

**Issue by ALBIHANY** [if-ai/ComfyUI-IF_AI_tools#34]
What am i doing wrong here !!! ?  Why i can't i get image to prompt, i also tried with other models i can only get txt2image work 

![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/4164766/a4d6220a-f2a9-45a9-bc83-50d8413b963c)

**Comment by ThomasRoyer24** [comment]
> What am i doing wrong here !!! ? Why i can't i get image to prompt, i also tried with other models i can only get txt2image work
> 
> ![image](https://private-user-images.githubusercontent.com/4164766/330614427-a4d6220a-f2a9-45a9-bc83-50d8413b963c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTk0MjAsIm5iZiI6MTcxNTc1OTEyMCwicGF0aCI6Ii80MTY0NzY2LzMzMDYxNDQyNy1hNGQ2MjIwYS1mMmE5LTQ1YTktYmM4My01MGQ4NDEzYjk2M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMDc0NTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWUzZTY3MDg4YzZiZGUzMTA3NmZkM2Q3Mzg4MmFkMDEwYjNlMDcwMGY3N2ZjYWI5Y2E2YzU4YWI1YTE3ZTE2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cyw1f-kv5Og7fIeVzsIcjtq31dx8RmO5Ta8qKwAnrXY)

You're using the wrong assistant. IF_PromptMKR is an assistant for text to image. **IF_PromptMKR_IMG** should be used for image to text. You can look here to see what each assistant does: 
https://github.com/if-ai/ComfyUI-IF_AI_tools/blob/main/presets/assistants.json

**Comment by if-ai** [comment]
> What am i doing wrong here !!! ? Why i can't i get image to prompt, i also tried with other models i can only get txt2image work
> 
> ![image](https://private-user-images.githubusercontent.com/4164766/330614427-a4d6220a-f2a9-45a9-bc83-50d8413b963c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzM4NjAsIm5iZiI6MTcxNTc3MzU2MCwicGF0aCI6Ii80MTY0NzY2LzMzMDYxNDQyNy1hNGQ2MjIwYS1mMmE5LTQ1YTktYmM4My01MGQ4NDEzYjk2M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTE0NjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjJhNmE4YTdjN2RiOTNlZGMwZjM2NTYxNTY5NjEzNjAxZTkyODRmNzYyODdlNDVlOTJkODg4NTc2ZDA0Njg2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vGJXLyZYuDcs22s-rjAGfqOIKBDtQEoST3G0UvnBnfE)

As @ThomasRoyer24 said but besides that it looks like you have the image still muted I muted it by default and there is a note over it saying you need to select the node and press CTRL+M to unmute also for working with images you need a multimodal model like llava, moondream or use the anthropic APIs I like haiku a lot and gpt4-o is also very strong. but in ollama and textgen you need a moondream or llava-llama3 or llava base models

**Comment by ALBIHANY** [comment]
Thank you very much for your comments and instructions, it's highly appreciated really, i also downloaded LLaVA 3 and the result are really impressive i will try the other models you mentioned, but i'm surprised you can also use  gpt4-o already i thought it's not accessible at the moment, i will also check that out

**Comment by ALBIHANY** [comment]
@if-ai  May i ask why moondream doesn't get me any results do i need to change some parameters? other models (such as llava-llama3) using the same parameters worked very well, thank you in advance.

![Untitled](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/4164766/de4e5c53-c905-476a-93be-cb80e44b1dbe)
