### ISSUE TITLE
ValueError: Invalid model selected:  for engine ollama. Available models:

### ISSUE THREAD

**Issue by apple-mark** [if-ai/ComfyUI-IF_AI_tools#35]
Error occurred when executing IF_ChatPrompt:

Invalid model selected: for engine ollama. Available models: []

File "F:\BaiduNetdiskDownload\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\BaiduNetdiskDownload\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\BaiduNetdiskDownload\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\BaiduNetdiskDownload\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 256, in describe_picture
raise ValueError(error_message)

**Comment by apple-mark** [comment]
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/126438999/29436276-c6e7-44a3-ab81-58b6ea69acf5)

**Comment by ThomasRoyer24** [comment]
> Error occurred when executing IF_ChatPrompt:
> 
> Invalid model selected: for engine ollama. Available models: []
> 
> File "F:\BaiduNetdiskDownload\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "F:\BaiduNetdiskDownload\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "F:\BaiduNetdiskDownload\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "F:\BaiduNetdiskDownload\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 256, in describe_picture raise ValueError(error_message)

For me, the problem comes from the fact that you haven't selected a model. You need to download a model from ollama, for example: ollama run mistral. Then use it on comfyui in **selected_model** in IF Chat Prompt.

**Comment by if-ai** [comment]
yes as @ThomasRoyer24  said you need to install ollama or use any of the other engines on the repo there are YT video guides on how to do it.  but essentially you go to https://ollama.com/ download and install ollama for your system then open terminal or command prompt  and type` ollama run impactframes/llama3_ifai_sd_prompt_mkr_q4km ` this will install the main recommended model to work with SD prompts there are several great models you can use in your computer for working with images you can use` ollama run llava-llama3` to install after that restart comfy the models should appear in the dropdown menu
