### ISSUE TITLE
Why does the image reverse prompt word appear to be inconsistent with the actual image?

### ISSUE THREAD

**Issue by shumoLR** [if-ai/ComfyUI-IF_AI_tools#41]
![QQ图片20240525233621](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/169419160/fc3f04e4-b2a2-4b4a-b02f-bb154303418a)
Hello, in the process of image to text, the text content does not match the image, please look at the image below, where do I set the problem?

**Comment by if-ai** [comment]
yes you need to use a llava model or other model that supports vision like the ones suggested on the repo readme  `ollama run llava:7b-v1.6-mistral-q5_K_M`

**Comment by shumoLR** [comment]
> yes you need to use a llava model or other model that supports vision like the ones suggested on the repo readme `ollama run llava:7b-v1.6-mistral-q5_K_M`

Ok, thank you very much. I'll try
