### ISSUE TITLE
Error occurred in one node after update

### ISSUE THREAD

**Issue by liulsg** [if-ai/ComfyUI-IF_AI_tools#44]
FETCH DATA from: G:\AI\ComfyUI_M\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "G:\AI\ComfyUI_M\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "G:\AI\ComfyUI_M\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\ComfyUI_M\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 78, in INPUT_TYPES
    "external_api_key": ("STRING", {"default": "", "multiline": false}),
                                                                ^^^^^
NameError: name 'false' is not defined

"external_api_key": ("STRING", {"default": "", "multiline": false}),     false The first letter is not capitalized

**Comment by wongpor** [comment]
same here

**Comment by if-ai** [comment]
Does it work now?

**Comment by liulsg** [comment]
@if-ai 
Error occurred when executing IF_ChatPrompt:

IFChatPrompt.describe_picture() got an unexpected keyword argument 'external_api_key'

File "G:\AI\ComfyUI_M\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\AI\ComfyUI_M\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\AI\ComfyUI_M\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))


Local model used

**Comment by elaurentin** [comment]
@if-ai @liulsg 
Same error, for Ollama, I commented out the line with
> #"external_api_key": ...

**Comment by if-ai** [comment]
Yes, I removed that for now, Thank you
