### ISSUE TITLE
How to install other models other than with "ollama run modelName"?

### ISSUE THREAD

**Issue by CoUIfy** [if-ai/ComfyUI-IF_AI_tools#49]
Hello,
This repo recommands several models that do not exist in the official supported list of models for ollama, 
for example Proteus-RunDiffusion and also a alternate version of nous hermes that do not exist here: https://ollama.com/library
My question is how do we install the other models that are recommanded here?

Thanks

**Comment by if-ai** [comment]
Yes the other models are meant for other engines you can look for models on the Ollama website. but for SD prompts you can use my https://ollama.com/impactframes/llama3_ifai_sd_prompt_mkr_q4km and for Image prompting `ollama run llava:7b-v1.6-mistral-q4_K_M ` The Proteus model is just a recommendation of an SD model that can understand prompts as SD3 comes out in a few days I expect even better models will be available soon the links are in the description  https://huggingface.co/dataautogpt3/ProteusV0.4

**Comment by CoUIfy** [comment]
Just to make sure I understand coreclty, you were suyggestin SD models, and not LLMs?
So what is the BEST LLM model you suggest (for making good prompts). The one you mentioend laalabva mistral one I suppose?

**Comment by if-ai** [comment]
Yes, there if prompt MKR is good a making prompts, then a Llava 1.6 if you want to play with images since you need a multimodal model for understanding images finally a good SD model to create images. But it works with other models aswell.
