### ISSUE TITLE
ValueError: Invalid model selected: llama3:latest for engine ollama. Available models: []

### ISSUE THREAD

**Issue by hjcxlp** [if-ai/ComfyUI-IF_AI_tools#51]
even if i had selected model llama3, yet still got this error. Or only some specific models are workable in this case?

Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 290, in describe_picture
    raise ValueError(error_message)
ValueError: Invalid model selected: llama3:latest for engine ollama. Available models: []

**Comment by xm1085** [comment]
我也是这个问题

**Comment by if-ai** [comment]
No all models should work can you make sure ollama is running before you launch comfy. I will check but it is possible that you have WSL and ollama is running in both sides on Linux and windows I had once that error and it turned out to be the model was not available on one of the installations. If you have windows and Linux versions of ComfyUI and Ollama try to run the ollama in the same sytem and quit the other `sytemctl stop ollama`

**Comment by shijian0417** [comment]
打开 最近的server.log，找到msg="Listening on 127.0.0.1:11434 (version 0.2.1)"，把端口1234改为11434

**Comment by if-ai** [comment]
is possible some people working on WSL or using a WIFI dongle get a mismatch localhost or 127.0.0.1 does not connect try open command prompt CMD and run `ipconfig` and use the IPv4 Address or maybe you are using docker try host.docker.internal

```
connection Wireless LAN adapter WiFi:
   Connection-specific DNS Suffix  . : Home
   IPv4 Address. . . . . . . . . . . : 192.168.0.7
```

**Comment by spiritform** [comment]
confused where the models are actually stored? can i download new ones?

**Comment by if-ai** [comment]
it depends of the provider you chose. Ollama download your models as blobs on a C:\Users\USERNAME\.ollama\models.

**Comment by spiritform** [comment]
oh, ok... so it automatically installs on c. is it possible to install ollama on a different drive or change the folder where the models are stored?

**Comment by if-ai** [comment]
No the way ollama install I think it doesn't let you to change the location but is possible to create symlinks to the blobs located on another drive but is complex to explain maybe ask the ai on how to do it  anyway it will only work if you symlink each blob I don't think symlinking the folder alone would work
