### ISSUE TITLE
Last June 10th update broke it for me [FIXED]

### ISSUE THREAD

**Issue by Laika92** [if-ai/ComfyUI-IF_AI_tools#53]
Hi there, dunno if the requirements have changed, I've been working perfectly fine with it all week but since I updated Comfy this morning The node install is in error 

![Screenshot 2024-06-10 133358](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/156084334/74ecaad7-59b9-4afa-9910-d473a23e6a7d)
![Screenshot 2024-06-10 133245](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/156084334/594adaf9-405c-4e7e-abd1-9e4a72c605ff)

tried uninstall, update requirements, install from url, update ollama, nothing works. 

Thanks in advance

**Comment by if-ai** [comment]
Sorry, I reverted back to the previous version should work like before If you have linux you can install the linux branch that has rag

**Comment by Laika92** [comment]
Running on Windows 11. I'll give it some time to kick in, still on the red side. 
![Screenshot 2024-06-10 143439](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/156084334/1ca4ab93-225f-4b7f-bc41-8805145a88a6)

Thank you! :)

**Comment by Laika92** [comment]
Nothing yet, installed requirements, uninstalled/installed several times. Manually, from manager.... still failing to load.

**Comment by Cal-DCosta** [comment]
Somehow the [ComfyUI-IF_AI_tools] from the manager does not install tried to do the usual uninstalled, reinstalled, cloned, installed requirements (via embedded bat and conda env), tried to install from url, updated Ollama, got the model for SD but nothing works. I hope it's not just me. The manager installs sometimes then after a while shows as error. 
![Screenshot 2024-06-10](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/164745785/7acbb6b7-542e-49a5-b273-7f42dee46f1d)

**Comment by May-Yaha** [comment]
+1

**Comment by lovinboi** [comment]
> Somehow the [ComfyUI-IF_AI_tools] from the manager does not install tried to do the usual uninstalled, reinstalled, cloned, installed requirements (via embedded bat and conda env), tried to install from url, updated Ollama, got the model for SD but nothing works. I hope it's not just me. The manager installs sometimes then after a while shows as error. ![Screenshot 2024-06-10](https://private-user-images.githubusercontent.com/164745785/338206308-7acbb6b7-542e-49a5-b273-7f42dee46f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjc2MzcsIm5iZiI6MTcxODAyNzMzNywicGF0aCI6Ii8xNjQ3NDU3ODUvMzM4MjA2MzA4LTdhY2JiNmI3LTU0MmUtNDlhNS1iMjczLTdmNDJkZWU0NmYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxMzQ4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODA2YWExNjYxZjEwOTM4MGE5NGJmZDY3NTU0M2VmNzc5NGFiNjAxZjhkZjk1ZTA4NDc5ODA0NTIzZjAyMDViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aqpaJsPufc8AhEmS-PhcfipJtJSpNjV2RuDVbsx2MiI)

This isn't just you. I am having the same issue. 
Fingers crossed.

**Comment by if-ai** [comment]
Again sorry I forgot to revert the requirements.txt now it should work

**Comment by al-swaiti** [comment]
at this moment after used all possible options its still not work!

**Comment by lovinboi** [comment]
for more context, I got this error 
Skip I:\AnimateDiff\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

> Again sorry I forgot to revert the requirements.txt now it should work

**Comment by Laika92** [comment]
After requirements.txt reverted: 

-Uninstalled folder manually,
-Installed via manager with error
-Deleted folder again
-Installed via git clone + embeeded_install.bat + requirements.txt 

Updated ComfyUI - All 

Still error
![Screenshot 2024-06-10 213524](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/156084334/102d7ae4-89d8-4cae-95ce-b2d1d3500d41)

I'll try tomorrow with a clean portable Comfy test install

Thank you!

**Comment by if-ai** [comment]
okay it was the init file  and the groq_api somehow they did not copy and were empty now it should work as I tested it on comfyui portable for windows

**Comment by lovinboi** [comment]
Perfect, it works fine.
You rock solid!

**Comment by Cal-DCosta** [comment]
Great! Thank you!

**Comment by Laika92** [comment]
Fixed it for me as well. **Thank you!**

**Comment by if-ai** [comment]
Sorry for the trouble I'll close this since is working now thank you

**Comment by Cal-DCosta** [comment]
Thank you, please keep the great work you do going. By the way I watched the ComfyUI Leadership Summit was great to put a face to the voice in your tutorials.

**Comment by Laika92** [comment]
+100 Thank you. I love this nodes.
