### ISSUE TITLE
I can't use open ai on IF chat prompt

### ISSUE THREAD

**Issue by ThomasRoyer24** [if-ai/ComfyUI-IF_AI_tools#54]
I added my api key in the environment variable for the user on my pc and I still got an error.
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/62610820/dce952ca-8196-4891-97f9-f2807cb6a54c)

**Comment by if-ai** [comment]
HI, Did you add it with the name `OPENAI_API_KEY` if you did then try adding as system variable 
.
