### ISSUE TITLE
Request to add nodes without default

### ISSUE THREAD

**Issue by alex13by** [if-ai/ComfyUI-IF_AI_tools#57]
I built a custom model in ollama, but I couldn't output correct content in the nodes. I hope to add nodes without any presets, so that I can directly use the defined model。

**Comment by if-ai** [comment]
Yes that feature already exist.  You can use None as assistant and other presets that way is not sending a system prompt or adding extras to the output

**Comment by alex13by** [comment]
Thank you very much. It is working now
