### ISSUE TITLE
Models folder ?

### ISSUE THREAD

**Issue by Crazy-Lion-QC** [if-ai/ComfyUI-IF_AI_tools#58]
Hi,
you suggest downloading additional models, but where is the models folder ? Seems like I can't find anything...
Thank You.

**Comment by gonzalu** [comment]
For Ollama, you do that in Ollama itself. 

example: ``` ollama run llava:13b```

that will download and run the model

**Comment by if-ai** [comment]
Yes like gonzalu said the models get automatically downloaded to an ollama folder on your computer the first time you run them if you want you can also use APIs which don't download a model and are more convenient for some people maybe you can try the groq api I have been using it for free for a long time
