### ISSUE TITLE
IF Chat Prompt Node: Unable to use Ollama in separate server on the network. 

### ISSUE THREAD

**Issue by gonzalu** [if-ai/ComfyUI-IF_AI_tools#59]
There is no way to define the IP of the Ollama Server, only the port. 

I am using the legacy nodes, but you mentioned the IF Chat Prompt will be the only node going forward. So, is there a way to specify the server IP on my network? 

Thank you

**Comment by gonzalu** [comment]
I think it was corrected. I now see the IP address field to define a server ... Thank you.

**Comment by if-ai** [comment]
Thanks if it happens again right click on the node and click reconstruct. I don't know why but this happens sometimes with some nodes including mine
