### ISSUE TITLE
Getting error IFChatPrompt Describe Picture

### ISSUE THREAD

**Issue by gonzalu** [if-ai/ComfyUI-IF_AI_tools#60]
Suddenly getting this error:

![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/32348862/edfbb437-47a9-42ae-beb7-389dd9306964)

```
!!! Exception during processing!!! IFChatPrompt.describe_picture() got an unexpected keyword argument 'image'
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: IFChatPrompt.describe_picture() got an unexpected keyword argument 'image'
```

**Comment by if-ai** [comment]
almost forgot to reply I can't reproduce the error on my side the SD prompt in ollama local models sometimes comes bad depending on the model you have if you have the recommended ones it should work okay and defenetly works great on the api models like haiku and gpt4o 
![YZt5W1HJaw](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/21185218/e87b4489-9eb2-4a70-96b7-53149624c45a)
![thorium_uRsDQVh7cK](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/21185218/4e1be313-dbca-42e9-9857-c8d0a2e0c8e5)

**Comment by gonzalu** [comment]
I was able to get rid of the problem by recreating the node itself... Seems that when I opened it from the saved workflow it did not pick up the settings correctly. Deleting the node and re-inserting the node fixed it for now. 

Thank you

**Comment by if-ai** [comment]
Fantastic glad you solve it on your own. Thanks for leaving the solution here.
