### ISSUE TITLE
assistant这个参数是做什么用的，切换之后感觉没有太大变化

### ISSUE THREAD

**Issue by water110** [if-ai/ComfyUI-IF_AI_tools#62]
![image](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/29881977/e33f52b3-5ae9-41a8-947c-6b9a6c9fcc52)
希望有详细使用说明

**Comment by if-ai** [comment]
I am sorry there are a few tutorials but they are in English all this are is a system prompt so the model behave differently   depending on the assistant  you can make your own by editing the json files and the reasoning quality of the model you choose plays a big roll on how good it follows the system prompt  
![explorer_t4e53qH1d5](https://github.com/user-attachments/assets/00f0a8d3-3801-4398-8f3d-a595a1fbd87a)
![Code_-_Insiders_8OY0Nu7Ctb](https://github.com/user-attachments/assets/0f115a7d-1cfd-4888-9ff1-7fe722ebb9bc)

**Comment by water110** [comment]
> I am sorry there are a few tutorials but they are in English all this are is a system prompt so the model behave differently depending on the assistant you can make your own by editing the json files and the reasoning quality of the model you choose plays a big roll on how good it follows the system prompt ![explorer_t4e53qH1d5](https://private-user-images.githubusercontent.com/21185218/348551797-00f0a8d3-3801-4398-8f3d-a595a1fbd87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTczNDIsIm5iZiI6MTcyMjYxNzA0MiwicGF0aCI6Ii8yMTE4NTIxOC8zNDg1NTE3OTctMDBmMGE4ZDMtMzgwMS00Mzk4LThmM2QtYTU5NWExZmJkODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE2NDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZTAzZGUzMmQ5MmUxMDQ1MmQ5Nzk1ZmY5MWNjMzM1YzcxOWJiMjcxNzBlNWNiMDA5MTkzNDQ1YTE0YTUyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tAliKkMztLlJ5jtsP35Rnzt2XFCVkhu1ZofuGSBl7_U) ![Code_-_Insiders_8OY0Nu7Ctb](https://private-user-images.githubusercontent.com/21185218/348551848-0f115a7d-1cfd-4888-9ff1-7fe722ebb9bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTczNDIsIm5iZiI6MTcyMjYxNzA0MiwicGF0aCI6Ii8yMTE4NTIxOC8zNDg1NTE4NDgtMGYxMTVhN2QtMWNmZC00ODg4LTlmZjEtN2ZlNzIyZWJiOWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE2NDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NGQyYzg3ZTgwZDY0ZGQ1NTM3NjRmZTcxY2M4MDgxMDU2N2E5ZjQ0NGI0MGJkZTQ0OWZlNDBlYmZiYmJkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y2NoXMyVUIjz4eZTbX8VJC6e0iKMZLS-R_90IffZq_c)

Thanks for your reply, I think I understand
