### ISSUE TITLE
Updating ComfyUI overwrites custom profiles

### ISSUE THREAD

**Issue by karl-von-knecht** [if-ai/ComfyUI-IF_AI_tools#64]
I edited the profiles.json file to add a custom profile. After doing an "Update All" in ComfyUI, my custom profile is gone.

**Comment by if-ai** [comment]
In the new latest version I m using a new strategy. I move it to the root of ComfyUI you need to download the folder IF_AI from the repo here and move it inside the input I:\ComfyUI\input\IF_AI that way it will never overwrite again unless you do it on purpose. Hope it helps
