### ISSUE TITLE
Please add more explanation

### ISSUE THREAD

**Issue by alex13by** [if-ai/ComfyUI-IF_AI_tools#69]
I don't quite understand why the "if display omni" node did not output after loading the image, resulting in an error on the "omost render canvas conditioning" node. Could you give me some instructions on how to use it?

**Comment by PrometheusDante** [comment]
Same for me, got the required node packs, everything loads perfectly, ollama connected and selected with the omost version, everything down to a T, still erroring out at the `if display omni` node, because of : 
Response from the IF Chat Prompt node 

> 
> Error in omost_tool: Code block must include valid canvas var!
> ```python
> # Initialize the image in memory using PIL library.
> from PIL import Image
> 
> def set_global_description(description: str, detailed_descriptions: list[str], tags: str, HTML_web_color_name: str):
>     pass  # Use a real Python function to initialize your description.

The only way to get it to run is by leaving the image node disconnected, which is extremely confusing as to why it's there in the first place if entirely unused.

**Comment by if-ai** [comment]
I made a video guide hope it helps maybe the only thing I didn't mention is that it might help to have the temperature bellow 0.5 https://youtu.be/Tku2COSKR88

**Comment by alex13by** [comment]
Thank you very much for your efforts

**Comment by PrometheusDante** [comment]
It's the `Load Image` node in the new omost example workflow. It just looks like it's supposed to be connected to the `IF Chat Prompt` node; but doing so the following error from omost doesn't tell you that the image input is the issue.
If you just add a small note between `Load Image` and `IF Chat Prompt` saying something like _"Do not input an image when using omost"_ new users would be less likely to run into that issue. 

Thank you for your time!

**Comment by if-ai** [comment]
Yes, I will upload the updated workflow with that disabled and a note node explaining that is just supposed to be used with other tools
