### ISSUE TITLE
Disable the `Error: <...> is required` log message

### ISSUE THREAD

**Issue by Gerkinfeltser** [if-ai/ComfyUI-IF_AI_tools#7]
Is it possible to disable the `Error: ... is required` log message if ollama is used?

I see the following frequently in my console log.
```
Error: ANTHROPIC_API_KEY is required
Error: OPENAI_API_KEY is required
Error: ANTHROPIC_API_KEY is required
Error: OPENAI_API_KEY is required
```

**Comment by if-ai** [comment]
Hi, I thought they were not required are you trying to use openai or anthropic api?  if so you need to set them up like in the readme if not, please set a dummy key that might work for the time being I will fix this next update so is not required.  Sorry I must have overlooked that

**Comment by Gerkinfeltser** [comment]
Hi, thanks for the reply! I went ahead and added system variables in Win 10 (dummy ones at least) and now the errors are gone but the server shell is constantly reporting:

```
API key found for ANTHROPIC_API_KEY
API key found for OPENAI_API_KEY
API key found for ANTHROPIC_API_KEY
API key found for OPENAI_API_KEY
```

**Comment by if-ai** [comment]
Fixed it, they will not show, anymore in the latest update, Thank you.
