### ISSUE TITLE
The example workflow doesn't output anything from tool_output

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [if-ai/ComfyUI-IF_AI_tools#70]
As per the description, there is no output so it causes the workflow to fail. The recommended omost nodes are also installed.

```
==================
IF_AI_tool_output:
==================
null
!!! Exception during processing!!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_omost\omost_nodes.py", line 325, in render_canvas
    numpy2pytorch(imgs=[OmostCanvas.render_initial_latent(canvas_conds)]),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_omost\lib_omost\canvas.py", line 370, in render_initial_latent
    conds[0]["color"]
    ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```
![image](https://github.com/user-attachments/assets/9aae44e2-282d-4db9-acd7-c787e2c2de6a)

**Comment by if-ai** [comment]
please try again leaving the stop field empty
![thorium_X1Chp2BqIC](https://github.com/user-attachments/assets/0034002c-6a0c-40c4-b05f-28b429ac0789)
![klsIGONHl0](https://github.com/user-attachments/assets/65246c23-67d3-451a-9b76-51bb81fa92df)

**Comment by GalaxyTimeMachine** [comment]
That's how I tried it to start with, but get the same error.

**Comment by GalaxyTimeMachine** [comment]
I've literally just dropped the omost_tool_wf.json into Comfy, changed the model to my path and I get the error when I run it.

**Comment by if-ai** [comment]
maybe I need to tweak the code but please try with a lower temp 0.2 or 0.5

**Comment by if-ai** [comment]
The only times I can reproduce this error is when I don't select omost tool in the last option of the node or when I select other engine or model that is not omost I also added a video here of me using it without cuts https://youtu.be/Tku2COSKR88
![RuXb5UxC4D](https://github.com/user-attachments/assets/78b20c92-972b-4af4-a347-94a9c372e111)

**Comment by GalaxyTimeMachine** [comment]
I'm using your example workflow, and have changed nothing, so the temperature is already set to 0.2.

**Comment by GalaxyTimeMachine** [comment]
It seems to have updated, but the error is identical.

**Comment by GalaxyTimeMachine** [comment]
Now it works! I hadn't spotted that it had changed the model to something that wasn't omost. Thank you!

**Comment by if-ai** [comment]
Excellent, glad it works. You should be able to work with normal temps 0.5 to 0.7 to have a more creative output.

**Comment by gonzalu** [comment]
I am running into this :( 

```

[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\server.py", line 435, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 105, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 52, in __init__
    self.agent_tools = self.load_agent_tools()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 74, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\ComfyUI\\ComfyUI\\input\\IF_AI\\presets\\agents

```

**Comment by gonzalu** [comment]
It broke all my workflows. 

This was working before the last update. I read in another post here, that I need to move a whole folder to the root of my ComfyUI directory. 

Thanks, but I am not comfortable with folders outside the custom node. 

I'll find other nodes to replace these wonderful nodes until and if there is a chance to have all functionality within the node folder. 

Thank you. I enjoyed these nodes before.
