### ISSUE TITLE
IF Chat prompt red node

### ISSUE THREAD

**Issue by Laika92** [if-ai/ComfyUI-IF_AI_tools#72]
Hello! I tried via main (zip) 
uninstalled / Installed via manager
tried to update via manager
Git clone repository
installed requirements in all custom nodes involved (basically omost and AI Tools)

And every time I get this
![Screenshot 2024-07-15 203531](https://github.com/user-attachments/assets/d8b48da5-131b-49d2-8379-2dffbac5022e)

_________________________________________________________

[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "C:\xxxxxxxxxx\ComfyUI_windows_portable\ComfyUI\server.py", line 435, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\xxxxxxxxxxx\ComfyUI_windows_portable\ComfyUI\server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxxxxxxxxxx\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 105, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "C:\xxxxxxxxxx\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 52, in __init__
    self.agent_tools = self.load_agent_tools()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxxxxxxxxxxxx\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 74, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\xxxxxxxxxxxxxxxxxxx\ComfyUI_windows_portable\\ComfyUI\\input\\IF_AI\\presets\\agents'

_________________________________________________________________

Not in a rush, the img to prompt and prompt to prompt nodes are working fine. They are not showing V2, though, (( I don't know if they should))

Thank you!

**Comment by if-ai** [comment]
Did you move the IF_AI folder from ComfyUI/Custom_nodes /ComfyUI-IF_AI_tools to insede the root of ComfyUI input folder? C:\xxxxxxxxxxxxxxxxxxx\ComfyUI_windows_portable\ComfyUI\input\IF_AI\

You should have the presets and agents C:\xxxxxxxxxxxxxxxxxxx\ComfyUI_windows_portable\ComfyUI\input\IF_AI\presets\agents

**Comment by Laika92** [comment]
Dammit! I missed point 3. Exactly, that was it. 
As an IT guy always ranting about people not reading the paper now I feel ashamed and humbled. :)
Thank you for this!  Edited to SOLVED.

**Comment by if-ai** [comment]
No worries it is my fault anyway as I didn't mentioned it in the video. I would put it on the node folder itself but I had to do it this way to avoid overwriting people's assistants and presets edits when updating the node. I will close this now thanks for reporting back, I am glad the issue was fixed.
