### ISSUE TITLE
7-17更新版本出现问题（There are issues with the updated version 7-17）

### ISSUE THREAD

**Issue by zhai-hello** [if-ai/ComfyUI-IF_AI_tools#74]
Cannot import F:\comfyui\custom_nodes\ComfyUI-IF_AI_tools module for custom nodes: No module named 'ComfyUI-IF_AI_tools.IFTextTyperNode'Updated version from July-17.However, the version with the omost node updated from July 7-16 
  has no issues.

**Comment by ZTWY35** [comment]
一样的问题，更新后就报这错了。
Same issue, gets this error after the update.   

ModuleNotFoundError: No module named 'ComfyUI-IF_AI_tools.IFTextTyperNode'

**Comment by Inmanguo** [comment]
same

**Comment by moddz** [comment]
same issue

**Comment by if-ai** [comment]
Sorry its up now
