### ISSUE TITLE
ModuleNotFoundError: No module named 'ComfyUI-IF_AI_tools.IFTextTyperNode'

### ISSUE THREAD

**Issue by emourdavid** [if-ai/ComfyUI-IF_AI_tools#76]
Hi,

I face with this issue after upgrade your node.

..../ComfyUI/custom_nodes/ComfyUI-IF_AI_tools/__init__.py", line 11, in <module>
    from .IFTextTyperNode import IFTextTyper
ModuleNotFoundError: No module named 'ComfyUI-IF_AI_tools.IFTextTyperNode'

I tried to pip install -r requirements.txt but this issue is still same. Do you have any ideas?

**Comment by if-ai** [comment]
Sorry I forgot to upload it yesterday. It's up now
