### ISSUE TITLE
No module named 'ComfyUI-IF_AI_tools.IFTextTyperNode'

### ISSUE THREAD

**Issue by lyx0206331** [if-ai/ComfyUI-IF_AI_tools#77]
After I updated the plugin, ComfyUI import failed, and terminal showed this: No module named 'ComfyUI-IF_AI_tools.IFTextTyperNode'

**Comment by if-ai** [comment]
I uploaded the text typer node about the time you post it please redownload the nodes it should work now I forgot to upload tha node last nioght
