### ISSUE TITLE
作者这里的路径是不是写错了，导致IFChatPromptNode无法加载，改了以后就正常了

### ISSUE THREAD

**Issue by cgl13207205048** [if-ai/ComfyUI-IF_AI_tools#79]
![1721230252485](https://github.com/user-attachments/assets/4b3baf9f-1754-4afe-ac8b-11026cacbe8c)

**Comment by if-ai** [comment]
No it was correct you need to move the IF_AI folder from ComfyUI/custom_nodes/ComfyUI-IF_AI_tools to the root of ComfyUI input folder like ComfyUI/input/IF_AI this is because you can edit and create your own presets and to prevent overwriting your  edits each time you update the node.

**Comment by cgl13207205048** [comment]
> No it was correct you need to move the IF_AI folder from ComfyUI/custom_nodes/ComfyUI-IF_AI_tools to the root of ComfyUI input folder like ComfyUI/input/IF_AI this is because you can edit and create your own presets and to prevent overwriting your edits each time you update the node.


I understand, thank you for your reply！
