### ISSUE TITLE
Can not load models and run ollama when ollama server is on (LINUX)

### ISSUE THREAD

**Issue by lognat0704** [if-ai/ComfyUI-IF_AI_tools#8]
Hi, thanks for the amazong tool. I try to use the example workflow on Linux, but It looks like even I run up the ollama server and the ip as same as  "IFprompt to prompt" node in Comfui. And my platform is Linux and not Windows. How do I fix the problem?

![Screenshot 2024-03-30 at 11 27 44 PM](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/9245626/a9ee5284-4f45-446c-a3b3-ce967ed21519)
![Screenshot 2024-03-30 at 11 32 27 PM](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/9245626/5a2a94b2-00b7-418b-bcc6-bcdff636c58d)

**Comment by if-ai** [comment]
Hi, do you have models on ollama? Because I am developing on Linux and was using all day without any issues.  I will try with the new ollama version maybe something changed.

**Comment by lognat0704** [comment]
Besides cmd ollama run and run it, do I miss out some steps? Maybe I should download the weights and manually copy to some place?? Btw,my linux machine is google VM.

Thanks in advance.

![Screenshot 2024-03-31 at 10 06 07 AM](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/9245626/c395a152-8c1e-439c-b0b4-b7e0823923ad)
![Screenshot 2024-03-31 at 10 07 10 AM](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/9245626/b3c93762-927f-4145-b550-34bb5e615da8)

**Comment by if-ai** [comment]
I am working on enabling virtual machines when is not on the same machine, Is your ComfyUI in the same VM machine?

**Comment by lognat0704** [comment]
It's google VM instances. And I run the ollama server and the comfyui server in the same google VM machine.

**Comment by if-ai** [comment]
> It's google VM instances. And I run the ollama server and the comfyui server in the same google VM machine.
I think they should work now. could you please try again you might need to enter the ip of the server on the base_ip, 

if not you should try set ollama host on the VM 
`sudo systemctl edit ollama.service`

add this to the file and save it

```
[Service]
Environment="OLLAMA_HOST=0.0.0.0"
```

```
sudo systemctl daemon-reload
sudo systemctl restart ollama
```

**Comment by rogeriodeoliveira** [comment]
Try recreate node 
![recreate](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/31973965/45af9fde-cb1e-458a-afbc-9b2e9bb26b29)

**Comment by if-ai** [comment]
@rogeriodeoliveira  Thank you , He posted this before the fix I think it should work now does it work for you? I am trying to close the issue, I teste it on my WSL and it works but will try it later on a GCP instance. Thanks
