### ISSUE TITLE
 An error occurred while retrieving information for the 'IF_ChatPrompt' node. Traceback (most recent call last):

### ISSUE THREAD

**Issue by wibur0620** [if-ai/ComfyUI-IF_AI_tools#84]
![image](https://github.com/user-attachments/assets/2f4d64cc-7692-4940-b946-dd9fd7a1927a)

**Comment by if-ai** [comment]
Yes you missed the Step **3. Move the IF_AI folder from the ComfyUI-IF_AI_tools to inside the root input ComfyUI/input/IF_AI** so for you it will be `D:\AI\ComfyUI\input\IF_AI`

**Comment by oktetopython** [comment]
thanks~
