### ISSUE TITLE
why the result so different?

### ISSUE THREAD

**Issue by K-O-N-B** [if-ai/ComfyUI-IF_AI_tools#87]
![image](https://github.com/user-attachments/assets/ceac25e3-e907-4cd5-a2a6-6e6ef501a182)

**Comment by if-ai** [comment]
yes the assistant has a system prompt that guides the description to be more like SD prompts you need to have a model with good reasoning normally you just need to ask something like  "make a SD prompt for the image" and use a vision model for it to work
