### ISSUE TITLE
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.

### ISSUE THREAD

**Issue by lemassykoi** [if-ai/ComfyUI-IF_AI_tools#88]
<code>FileNotFoundError: '[...]\\ComfyUI_windows_portable_nvidia\\ComfyUI\\input\\IF_AI\\presets\\stop_strings.json'</code>

but I can't find any reference to that file. Can you please tell me its content? Thanks

**Comment by if-ai** [comment]
yes you need to follow step 3 on the readme and manually move the files from the custom node  IF_AI folder into the root ComfyUI\input\IF_AI\ I did this to prevent overriding your presets each time you update
