### ISSUE TITLE
running error after update.

### ISSUE THREAD

**Issue by K-O-N-B** [if-ai/ComfyUI-IF_AI_tools#90]
![image](https://github.com/user-attachments/assets/ce9919ab-2ad9-4747-a997-2dc7cb7369e9)

I've re-download the models, still error.

**Comment by K-O-N-B** [comment]
the command line work fine.

![image](https://github.com/user-attachments/assets/425a3083-c26f-4144-a2f4-60716e04d506)

**Comment by if-ai** [comment]
did move place the IF_AI folder from the custom_nodes/ComfyUI-IF_AI_tools/IF_AI to the root of comfy ComfyUI/input/IF_AI like it says in step3?

**Comment by K-O-N-B** [comment]
I don't know the code, but it's worked after move the folder.
