### ISSUE TITLE
IF Chat Node error

### ISSUE THREAD

**Issue by yogeshnichal** [if-ai/ComfyUI-IF_AI_tools#91]

**Comment by yogeshnichal** [comment]
![Shot 0016](https://github.com/user-attachments/assets/07fe486f-f8d0-4614-bcb0-d3c453266ccd)

**Comment by if-ai** [comment]
what is the error?

**Comment by yogeshnichal** [comment]
Thanx for responce but is sloved IF_AI folder put into input folder
